import "../globals.css";
//import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Appbar from "@/components/appbar";
import Card from "@/components/card";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

/**
export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};
**/

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
			<div className={inter.className}>
				<Appbar />
				{/* main */}
				<main className="max-w-6xl w-full m-auto">
					<div className="flex justify-space w-full p-4 gap-4">
						{/* left menu */}
						<div className="lg:block xs:hidden flex-0">
							<Card>
								<div className="w-64 min-h-20 p-5">
									<Link href="#" className="hover:underline leading-8">
										Home
									</Link>
									<br />
									<br />
									<Link href="#" className="hover:underline">
										Logs
									</Link>
								</div>
							</Card>
						</div>
						
						{/* right content */}
						<div className="flex-1">{children}</div>
					</div>
				</main>
			</div>
	);
}
